parameters: {}
environment: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    actions:
      - name: hello
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}
      - name: authenticate
        mail: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

        
