parameters: {}
environment: {}
packages:
  - name: sample
    environment: 
      DATABASE_USERNAME: ${host}
      DATABASE_PORT: ${port}
      DATABASE_USER: ${user}
      DATABASE_PASSWORD: ${password}
      DATABASE_NAME: ${dbname}
    parameters: {}
    actions:
      - name: hello
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}
      - name: authenticate
        mail: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

        
